# Generated by Django 3.1.5 on 2021-01-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body',
            field=models.CharField(default='I hope this Works', max_length=360),
            preserve_default=False,
        ),
    ]
