# Generated by Django 3.1.5 on 2021-01-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(default='https://mscshankar.files.wordpress.com/2013/10/oops-concept.png', max_length=360),
            preserve_default=False,
        ),
    ]
