# Generated by Django 3.1.5 on 2021-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isOpen',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
